"""Dispatcher texts per recommendation, generated by YandexGPT (team repo) and cached as files.

The screen only reads `<run_dir>/explanations/yandexgpt/<rec_id>.txt` + `meta.json` (own dir, never
mixed with person 4's `explanations/<id>.txt`); this module writes them (meta.json last).
Any failure leaves the template `reason` in place (meta source "mock")."""

from __future__ import annotations

import importlib
import json
import os
import sys
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from metro_control.events import station_reasons
from metro_control.line import load_line
from metro_control.screen import (
    ACTION_TITLES_RU,
    actionable,
    load_bundle,
    load_recommendations,
    rec_evidence,
)
from metro_control.team_forecast import read_team_context
from metro_control.timeutil import to_msk

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TEAM_REPO = Path("/root/sirius/metro-petersburg")
MODULE = "external_data.dispatcher_text"
MAX_REASONS = 3
SUBDIR = "explanations/yandexgpt"


def _has_module(root: Path) -> bool:
    return (root / "external_data" / "dispatcher_text.py").is_file()


def team_repo() -> Path | None:
    env = os.environ.get("METRO_TEAM_REPO")
    if env:
        return Path(env)
    for cand in (PROJECT_ROOT.parent, DEFAULT_TEAM_REPO):
        if _has_module(cand):
            return cand
    return None


def _names() -> tuple[dict[str, str], dict[str, tuple[str, str]]]:
    line = load_line()
    names = {s.id: s.name_ru for s in line.stations}
    segs = {s.id: (s.from_station, s.to_station) for s in line.segments}
    return names, segs


def _where(target: str, names: dict[str, str], segs: dict) -> tuple[str, list[str]]:
    if target in segs:
        a, b = segs[target]
        return f"{names[a]} → {names[b]}", [a, b]
    if target in names:
        return names[target], [target]
    return target, []


def forecast_items(run_dir: Path | str) -> list[dict[str, Any]]:
    d = Path(run_dir)
    bundle = load_bundle(d)
    load_pkg = bundle["load"].package if bundle["load"].ok else None
    ctx = read_team_context(d)
    names, segs = _names()
    items = []
    for rec in actionable(load_recommendations(d, bundle["recommendation"]).items):
        p = rec.payload
        seg_text, stations = _where(p.target, names, segs)
        slots = (
            sorted({r.ts for r in load_pkg.payload if p.start <= r.ts < p.end}) if load_pkg else []
        )
        reasons: list[str] = []
        if ctx and slots:
            by_st = station_reasons(ctx, slots)
            for sid in stations:
                for texts in by_st.get(sid, []):
                    reasons.extend(t for t in texts if t not in reasons)
        item: dict[str, Any] = {
            "rec_id": p.recommendation_id,
            "action": p.action,
            "action_text": ACTION_TITLES_RU[p.action],
            "segment": seg_text,
            "window": f"{to_msk(p.start):%H:%M}–{to_msk(p.end):%H:%M}",
            "as_of": f"{to_msk(p.as_of):%H:%M}",
            "reasons": reasons[:MAX_REASONS],
        }
        ev = rec_evidence(rec, load_pkg)
        if ev and ev["peak"]:
            pk = ev["peak"]
            item.update(
                peak_ratio=pk["r"],
                ratio_limit=ev["r_on"],
                demand=pk["demand"],
                capacity=pk["capacity"],
            )
        items.append(item)
    return items


def sim_items(sim_dir: Path | str) -> list[dict[str, Any]]:
    from metro_control.sim_view import sim_payload
    from metro_control.timeline import load_timeline

    d = Path(sim_dir)
    tl, _ = load_timeline(d)
    if tl is None:
        return []
    actions = []
    for ln in (d / "actions.jsonl").read_text(encoding="utf-8").splitlines():
        try:
            row = json.loads(ln)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict) and row.get("recommendation_id"):
            actions.append(row)
    names, segs = _names()
    acts = sim_payload(tl, names, actions, "mock")["actions"]
    by_id = {a["rec_id"]: a for a in acts if a.get("rec_id")}
    items = []
    for ac in actions:
        rid = ac["recommendation_id"]
        act = by_id.get(rid)
        seg_text, _ = _where(str(ac.get("target", "")), names, segs)
        item: dict[str, Any] = {
            "rec_id": rid,
            "action": ac.get("action"),
            "action_text": ACTION_TITLES_RU.get(str(ac.get("action")), str(ac.get("action"))),
            "segment": seg_text,
            "window": act["win"] if act else None,
            "as_of": act["time"] if act else None,
        }
        ba = act.get("ba") if act else None
        if ba:
            item["ratio_after"] = ba["peak"][1]
            if ba.get("trains"):
                item["trains_before"], item["trains_after"] = ba["trains"]
            item["left_behind_before"], item["left_behind_after"] = ba["left"]
        items.append(item)
    return items


def _default_explain(items: list[dict]) -> dict[str, str]:
    root = team_repo()
    if root is None:
        raise RuntimeError("team repo with external_data/dispatcher_text.py not found")
    sys.path.insert(0, str(root))
    try:
        mod = importlib.import_module(MODULE)
        return mod.explain_recommendations(items)
    finally:
        sys.path.remove(str(root))


def explain_run(
    run_dir: Path | str,
    *,
    kind: str = "forecast",
    explain: Callable[[list[dict]], dict[str, str]] | None = None,
) -> dict[str, Any]:
    d = Path(run_dir)
    out_dir = d / SUBDIR
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.txt"):
        old.unlink()
    try:
        items = sim_items(d) if kind == "sim" else forecast_items(d)
        ids = {i["rec_id"] for i in items}
        texts = (explain or _default_explain)(items)
        texts = {k: str(v).strip() for k, v in texts.items() if k in ids and str(v).strip()}
        if not texts:
            raise RuntimeError("no texts returned")
    except Exception as e:  # noqa: BLE001 - the screen must never break on the LLM
        meta = {"source": "mock", "error": (str(e).splitlines() or [e.__class__.__name__])[0]}
        (out_dir / "meta.json").write_text(json.dumps(meta, ensure_ascii=False), encoding="utf-8")
        return meta
    for rid, text in texts.items():
        (out_dir / f"{rid}.txt").write_text(text, encoding="utf-8")
    meta = {
        "source": "yandexgpt",
        "model": os.environ.get("YANDEX_MODEL"),
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "n": len(texts),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, ensure_ascii=False), encoding="utf-8")
    return meta
